apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: winter-soldier
    app.kubernetes.io/part-of: winter-soldier
    app: winter-soldier
  name: winter-soldier
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: winter-soldier
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: winter-soldier
    spec:
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        image: {{ .Values.image }}
        name: manager
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.graceperiod }}
      serviceAccount: winter-soldier
      serviceAccountName: winter-soldier