apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: winter-soldier
    app.kubernetes.io/part-of: winter-soldier
  name: winter-soldier
  namespace: {{ .Release.Namespace }}