apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-cert-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-cert-role
subjects:
- kind: ServiceAccount
  name: argocd-cert-sa
  namespace: devtroncd