apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-cert-role
rules:
- apiGroups: [""]
  resources:
  - pods
  - secrets
  verbs:
  - create
  - get
  - list
  - delete
  - update
  - patch