kubewatch:
  acdNamespace: devtroncd
  replicaCount: 1
  env:
    - name: DEFAULT_NAMESPACE
      value: "devtron-ci"
    - name: CI_INFORMER
      value: "true"
    - name: ACD_INFORMER
      value: "true"
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 128Mi
      cpu: 100m
  image:
    repo: quay.io/devtron/kubewatch
    tag: v0.1.0
  podLabels:
    component: kubewatch
tolerations: []
# - key: "key1"
#   operator: "Equal"
#   value: "value1"
#   effect: "NoSchedule"
affinity: {}
  # nodeAffinity:
  #   required:
  #     nodeSelectorTerms:
  #     - matchExpressions:
  #       - key: topology.kubernetes.io/zone
  #         operator: In
  #         values:
  #         - us-east-2a
  #       - key: topology.kubernetes.io/region
  #         operator: In
  #         values:
  #         - us-east-2
