apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cm
  namespace: {{ .Release.Namespace }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    app: svn-git-sync
data:
{{ toYaml $.Values.configs | indent 2 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    app: svn-git-sync
type: Opaque
data:
{{- range $k, $v := $.Values.secrets }}
  {{ $k }}: {{ $v | b64enc | quote }}
{{- end }}
{{- if $.Values.CUSTOM_BRANCHES_TO_SYNC }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-branches-cm
  namespace: {{ .Release.Namespace }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    app: svn-git-sync
data:
  custom_branches.txt: |
  {{- range $.Values.CUSTOM_BRANCHES_TO_SYNC }}
{{ . | indent 4 }}
  {{- end }}
{{- end }}