apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: svn-git-sync
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      release: {{ .Release.Name }}
  replicas: 1
  minReadySeconds: 60
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        release: {{ .Release.Name }}
      {{- if .Values.podLabels }}{{ toYaml .Values.podLabels | nindent 8 }}
      {{- end }}
      {{- if .Values.podAnnotations }}
      annotations: {{ toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      {{- if and $.Values.persistence.enabled $.Values.CUSTOM_BRANCHES_TO_SYNC }}
      volumes:
        - name: {{ .Release.Name }}-volume
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pvc
        - name: {{ .Release.Name }}-branches
          configMap:
            name: {{ .Release.Name }}-branches-cm
      {{- else if $.Values.persistence.enabled }}
      volumes:
        - name: {{ .Release.Name }}-volume
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pvc
      {{- else if $.Values.CUSTOM_BRANCHES_TO_SYNC }}
      volumes:
        - name: {{ .Release.Name }}-branches
          configMap:
            name: {{ .Release.Name }}-branches-cm
      {{- end }}
      terminationGracePeriodSeconds: 30
      {{- if .Values.autoRestart }}
      serviceAccountName: {{ .Release.Name }}
      {{- end }}
      restartPolicy: Always
      containers:
        - name: {{ .Release.Name }}
          image: {{ $.Values.image }}
          imagePullPolicy: {{ $.Values.imagePullPolicy }}
          envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-cm
          - secretRef:
              name: {{ .Release.Name }}-secret
          {{- if and $.Values.persistence.enabled $.Values.CUSTOM_BRANCHES_TO_SYNC }}
          volumeMounts:
            - name: {{ .Release.Name }}-volume
              mountPath: /app
            - name: {{ .Release.Name }}-branches
              mountPath: /app/{{ $.Values.configs.REPO_NAME }}/
          {{- else if $.Values.persistence.enabled }}
          volumeMounts:
            - name: {{ .Release.Name }}-volume
              mountPath: /app
          {{- else if $.Values.CUSTOM_BRANCHES_TO_SYNC }}
          volumeMounts:
            - name: {{ .Release.Name }}-branches
              mountPath: /app/{{ $.Values.configs.REPO_NAME }}/
          {{- end }}
        {{- if .Values.autoRestart }}
        - name: {{ .Release.Name }}-cron
          image: quay.io/devtron/svn-git-sync:cron
          imagePullPolicy: {{ $.Values.imagePullPolicy }}
          envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-cm
          {{- if $.Values.persistence.enabled }}
          volumeMounts:
            - name: {{ .Release.Name }}-volume
              mountPath: /app
          {{- end }}
        {{- end }}
          
          