apiVersion: v1
kind: Service
metadata:
  name: discord-alertmanager-svc
  labels:
    app: discord
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: discord
      port: 9094
      targetPort: {{ .Values.targetport}}
      protocol: TCP
  selector:
    app: discord

    
